# Generated by Django 5.0.3 on 2024-09-24 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miniapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='featured',
            field=models.CharField(default='null', max_length=300, verbose_name='Featured Event'),
        ),
    ]
